import React from 'react'
import "./styles.css"

const SizeGuide = () => {
  return (
    <div className='size-guide-parent-container container'>
        <h3>Find your correct show size in the chart below</h3>
        <h3>Scroll horizontally to see more sizes</h3>
        <div className='table-wrapper'>
            <table>
                <tr>
                    <th className='headcol'>US-Men's</th>
                    <td>3.5</td>
                    <td>4</td>
                    <td>4.5</td>
                    <td>5</td>
                    <td>5.5</td>
                    <td>6</td>
                    <td>6.5</td>
                    <td>7</td>
                    <td>7.5</td>
                    <td>8</td>
                    <td>8.5</td>
                    <td>9</td>
                    <td>9.5</td>
                    <td>10</td>
                    <td>10.5</td>
                    <td>11</td>
                    <td>11.5</td>
                    <td>12</td>
                    <td>12.5</td>
                    <td>13</td>
                    <td>13.5</td>
                    <td>14</td>
                    <td>14.5</td>
                    <td>15</td>
                    <td>15.5</td>
                    <td>16</td>
                    <td>16.5</td>
                    <td>17</td>
                    <td>17.5</td>
                    <td>18</td>
                    <td>18.5</td>
                    <td>19</td>
                    <td>19.5</td>
                    <td>20</td>
                </tr>
                <tr>
                    <th className='headcol'>US-Women's</th>
                    <td>5</td>
                    <td>5.5</td>
                    <td>6</td>
                    <td>6.5</td>
                    <td>7</td>
                    <td>7.5</td>
                    <td>8</td>
                    <td>8.5</td>
                    <td>9</td>
                    <td>9.5</td>
                    <td>10</td>
                    <td>10.5</td>
                    <td>11</td>
                    <td>11.5</td>
                    <td>12</td>
                    <td>12.5</td>
                    <td>13</td>
                    <td>13.5</td>
                    <td>14</td>
                    <td>14.5</td>
                    <td>15</td>
                    <td>15.5</td>
                    <td>16</td>
                    <td>16.5</td>
                    <td>17</td>
                    <td>17.5</td>
                    <td>18</td>
                    <td>18.5</td>
                    <td>19</td>
                    <td>19.5</td>
                    <td>20</td>
                    <td>20.5</td>
                    <td>21</td>
                    <td>21.5</td>
                </tr>
                <tr>
                    <th className='headcol'>US-kid's</th>
                    <td>3.5Y</td>
                    <td>4Y</td>
                    <td>4.5Y</td>
                    <td>5Y</td>
                    <td>5.5Y</td>
                    <td>6Y</td>
                    <td>6.5Y</td>
                    <td>7Y</td>
                    <td>7.5Y</td>
                    <td>8Y</td>
                    <td>8.5Y</td>
                    <td>9Y</td>
                    <td>9.5Y</td>
                    <td>10Y</td>
                    <td>10.5Y</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <th className='headcol'>UK</th>
                    <td>3</td>
                    <td>3.5</td>
                    <td>4</td>
                    <td>4.5</td>
                    <td>5</td>
                    <td>5.5</td>
                    <td>6</td>
                    <td>6</td>
                    <td>6.5</td>
                    <td>7</td>
                    <td>7.5</td>
                    <td>8</td>
                    <td>8.5</td>
                    <td>9</td>
                    <td>9.5</td>
                    <td>10</td>
                    <td>10.5</td>
                    <td>11</td>
                    <td>11.5</td>
                    <td>12</td>
                    <td>12.5</td>
                    <td>13</td>
                    <td>13.5</td>
                    <td>14</td>
                    <td>14.5</td>
                    <td>15</td>
                    <td>15.5</td>
                    <td>16</td>
                    <td>16.5</td>
                    <td>17</td>
                    <td>17.5</td>
                    <td>18</td>
                    <td>18.5</td>
                    <td>19</td>
                </tr>
                <tr>
                    <th className='headcol'>CM /JP</th>
                    <td>22.5</td>
                    <td>23</td>
                    <td>23.5</td>
                    <td>23.5</td>
                    <td>24</td>
                    <td>24</td>
                    <td>24.5</td>
                    <td>25</td>
                    <td>25.5</td>
                    <td>26</td>
                    <td>26.5</td>
                    <td>27</td>
                    <td>27.5</td>
                    <td>28</td>
                    <td>28.5</td>
                    <td>29</td>
                    <td>29.5</td>
                    <td>30</td>
                    <td>30.5</td>
                    <td>31</td>
                    <td>31.5</td>
                    <td>32</td>
                    <td>32.5</td>
                    <td>33</td>
                    <td>33.5</td>
                    <td>34</td>
                    <td>34.5</td>
                    <td>35</td>
                    <td>35.5</td>
                    <td>36</td>
                    <td>36.5</td>
                    <td>37</td>
                    <td>37.5</td>
                    <td>38</td>
                </tr>
                <tr>
                    <th className='headcol'>EU</th>
                    <td>35.5</td>
                    <td>36</td>
                    <td>36.5</td>
                    <td>37.5</td>
                    <td>38</td>
                    <td>38.5</td>
                    <td>39</td>
                    <td>40</td>
                    <td>40.5</td>
                    <td>41</td>
                    <td>42</td>
                    <td>42.5</td>
                    <td>43</td>
                   
                    <td>44</td>
                    <td>44.5</td>
                    <td>45</td>
                    <td>45.5</td>
                    <td>46</td>
                    <td>47</td>
                    <td>47.5</td>
                    <td>48</td>
                    <td>48.5</td>
                    <td>49</td>
                    <td>49.5</td>
                    <td>50</td>
                    <td>50.5</td>
                    <td>51</td>
                    <td>51.5</td>
                    <td>52</td>
                    <td>52.5</td>
                    <td>53</td>
                    <td>53.5</td>
                    <td>54</td>
                    <td>54.5</td>
                </tr>
            </table>
        </div>
    </div>
  )
}

export default SizeGuide